### ISSUE TITLE
Add to docs how to get shareable link

### ISSUE THREAD

**Issue by m-abdelwahab** [excalidraw/gatsby-embedder-excalidraw#1]
I didn't know that I can share my work through a link on excalidraw.

My suggestion is to add one of the following:

"To get a shareable link for your work on excalidraw, export your work and press the link icon 🔗"

Or 
![export](https://user-images.githubusercontent.com/27310414/81410113-83990700-9140-11ea-8a54-5d488cce9175.gif)

add this GIF

**Comment by m-abdelwahab** [comment]
if you would like me to upload the GIF please tell me which export settings work for GitHub so that it's visible

**Comment by trevorblades** [comment]
Fixed by a3de975ecebca910d7afc92dfa196d998788cc75. Thanks for the suggestion @m-abdelwahab 🎉
