### ISSUE TITLE
Bug Stuck on Building development bundle

### ISSUE THREAD

**Issue by denvash** [excalidraw/gatsby-embedder-excalidraw#13]
Hi,

Going through the readme explanation, when adding `gatsby-embedder-excalidraw` to `gatsbyRemarkPlugins` of `gatsby-plugin-mdx` and running `gatsby develop`, the **building bundle stuck and never finishes**.

Reproducible example in codesandbox:

[![Edit Gatsby Embedder Excaildraw Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gatsby-embedder-excaildraw-bug-e38zt?fontsize=14&hidenavigation=1&theme=dark)

**Also,** cloning the repo (installing the dependencies etc.) and running the example will result in the same issue.

**Comment by trevorblades** [comment]
Ah I see! You mentioned that you added `gatsby-embedder-excalidraw` as a Gatsby remark plugin for MDX, but instead you need to add `gatsby-remark-embedder` to `gatsbyRemarkPlugins` and then require this library as a custom transformer. You can see this technique being used in the example here: https://github.com/excalidraw/gatsby-embedder-excalidraw#configure-plugins

**Comment by denvash** [comment]
> Ah I see! You mentioned that you added `gatsby-embedder-excalidraw` as a Gatsby remark plugin for MDX, but instead you need to add `gatsby-remark-embedder` to `gatsbyRemarkPlugins` and then require this library as a custom transformer.
> 
> You can see this technique being used in the example here: https://github.com/excalidraw/gatsby-embedder-excalidraw#configure-plugins

The config is configured according to docs.

```
plugins: [
    {
      resolve: "gatsby-plugin-mdx",
      options: {
        gatsbyRemarkPlugins: [
          {
            resolve: "gatsby-remark-embedder",
            options: {
              customTransformers: [require("gatsby-embedder-excalidraw")]
            }
          }
        ]
      }
    }
  ]
```

As I mentioned, there is a reproducible example of the problem in [codesandbox](https://codesandbox.io/s/gatsby-embedder-excaildraw-bug-e38zt?fontsize=14&hidenavigation=1&theme=dark&file=/gatsby-config.js:279-589), and the example in this repo not working as well.

Here is the error (appeared in the sandbox, on local it stuck)

```
  Error: The following error appeared while processing 'https://excalidraw.com/#  json=5695519967936512,sLhjTgn1_wB1iVLLquX6Fg':
  Failed to launch the browser process!
  /sandbox/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chro  me: error while loading shared libraries: libX11-xcb.so.1: cannot open shared   object file: No such file or directory
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troub  leshooting.md
```

**Comment by codepunkt** [comment]
You have some libraries missing that are required to run puppeteer

**Comment by trevorblades** [comment]
@denvash I just published a new version a few days ago that should address any build hanging or failing issues. Could you please try again? We were seeing some issues with newer versions of puppeteer (a dependency of this plugin), so make sure to clear out old dependencies before reinstalling. 😇
