### ISSUE TITLE
gatsby-remark-embedder is on version 4

### ISSUE THREAD

**Issue by lipis** [excalidraw/gatsby-embedder-excalidraw#28]
- https://github.com/MichaelDeBoey/gatsby-remark-embedder/tags
- https://github.com/excalidraw/gatsby-embedder-excalidraw/blob/master/package.json#L27

**Comment by trevorblades** [comment]
I just updated the `peerDependency` on `gatsby-remark-embedder` to >= 2 in 357c87655802aec95224aaa2718946af41b5dbc6. The breaking changes to the package have to do with updates to their Instagram/Twitch embeds.
